Python Array 和 Numpy Array 的区别?
    - 处理数组更快：NumPy和Pandas的底层逻辑是用C语言写的，C这种底层语言自然能更快更有效率地调用电脑资源
    - 处理数组更灵活：NumPy 库中提供更多处理 Array 的方式，比如合并分割数组、对数组进行统计计算等等

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [7]:
type(a)

numpy.ndarray

In [13]:
# array create

b = np.array([2, 3, 5, 8])
b

dtype('float64')

In [ ]:
b.dtype


In [14]:
c = np.array([2.2 ,3.2 , 2.4])
c
c.dtype

dtype('float64')

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 5), dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [17]:
np.empty((2, 3))

array([[-2.00000000e+000, -2.00000000e+000,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [19]:
np.arange(10, 40, 5)

array([10, 15, 20, 25, 30, 35])

In [20]:
np.arange(0.2 , 4, 0.3)

array([0.2, 0.5, 0.8, 1.1, 1.4, 1.7, 2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8])